routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/server', function(){
    return view('frontend.button');
});

Route::get('admin', 'Auth\LoginController@loginAdmin')->middleware('role_web')->name('login.admin');
Route::get('/vote', function () {
    return view('voting.login');
});

Route::get('/', function () {
    return view('landing');
});

 Route::post('/vote', 'LoginsController@login');

//Route::post('/voting', 'LoginController@login');

Route::post('/pilih', 'LoginsController@pilih');
Route::get('/berhasil', 'LoginsController@berhasil');

Route::post('/auth/login', ['as' => 'login', 'uses' => 'Auth\LoginController@login']);
Route::get('/auth/logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);

Route::group(['prefix' => 'backend', 'namespace' => 'Backend', 'middleware' => ['auth', 'role_web:admin' ]], function() {
    Route::get('/mahasiswas/import', 'MahasiswaController@toImport')->name('backend.mahasiswa.toImport');
    Route::get('/mahasiswas/export', 'MahasiswaController@export')->name('backend.mahasiswa.export');
    Route::post('mahasiswas/import', 'MahasiswaController@import')->name('backend.mahasiswa.import');
    Route::get('/', array('as' => 'backend.dashboard.index', 'uses' => 'DashboardController@index'));
    Route::resource('users', 'UsersController');
    Route::resource('kelas', 'KelasController');
    Route::resource('mahasiswa', 'MahasiswaController');
    Route::resource('candidates', 'CandidatesController');
    Route::resource('token', 'TokenController');
    Route::resource('logs_web', 'LogsWebController');
    Route::resource('devices', 'DevicesController');
    Route::resource('suara', 'SuaraController');
    Route::resource('dashboard', 'DashboardController');
    Route::get('regenerate/token/{id}', 'TokenController@regenerate');

});
Route::get('/backend/token', 'Backend\TokenController@index')->name('token');
Route::get('/backend/mahasiswas', 'Backend\MahasiswaController@index')->name('mahasiswa');
Route::get('/backend/mahasiswa/des/{id}', 'Backend\MahasiswaController@destroy')->name('mahasiswadestroy');
Route::get('/backend/delete-token/des/{id}', 'Backend\TokenController@destroy')->name('tokendestroy');

Route::group(['prefix' => 'saksi', 'namespace' => 'Saksi', 'middleware' => ['auth', 'role_web:saksi' ]], function() {
    Route::get('/', 'DashboardController@index')->name('saksi.dashboard.index');
    Route::resource('suara', 'SuaraController');
    Route::resource('dashboard', 'DashboardController');
    Route::resource('mahasiswa', 'MahasiswaController');
    Route::resource('dashboard', 'DashboardController');
});

Route::group(['prefix' => 'gen-token', 'namespace' => 'GenToken', 'middleware' => ['auth', 'role_web:gen-token' ]], function() {
    Route::get('/', 'TokenController@index')->name('gen-token.dashboard.index');
    Route::resource('token', 'TokenController', ['as' => 'token']);
    Route::get('regenerate/token/{id}', 'TokenController@regenerate');
    Route::resource('dashboard', 'DashboardController');
    Route::get('regenerate/token/{id}', 'TokenController@regenerate');
});
Route::get('/bem/token', 'GenToken\TokenController@index')->name('tokenbem');

Route::get('validasi/{nrp}', 'GetmahasiswaController@validasi');

Route::group(['prefix' => 'backend', 'namespace' => 'Backend'], function() {
    Route::get('/token/show/{id}', ['as' => 'backend.token.show', 'uses' => 'TokenController@show']);
});

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    return "Cache is cleared";
});

app/Models/Token.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Token extends Model
{
    protected $table = 'token';

    protected $fillable = [
        'nrp',
        'token',
        'status_token',
    ];
}

app/Http/Controllers/Backend/TokenController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Mahasiswa;
use App\Models\Token;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Datatables;

class TokenController extends Controller
{
    public function index(Request $request)
    {
        $data['data'] = Token::orderBy('id', 'DESC')->get();
        $data['mahasiswa'] = Mahasiswa::where('status_pilih', '=', 'Belum')->get();
        if ($request->ajax()) {
            $token = Token::orderBy('id', 'DESC')->get();

            return DataTables::of($token)
                ->addColumn('durasi', function ($data) {
                    return '<p class="timer" data-create="'.$data->updated_at.'" data-id="'.$data->id.'" data-status="'.$data->status_token.'"></p>';
                })
                ->addColumn('action', function ($data) {
                    $button = '<a href="'.url('backend/regenerate/token/'.$data->id).'" onclick="return confirm('.'`Are you sure?`'.')" class="btn btn-info"><i class="fa fa-pencil"></i> Regenerate</a>';
                    //                    $button .= '<a href="' . route('mahasiswadestroy', $data->id) . '" class="btn btn-danger" onclick="return confirm('.'Are you sure?'.')"><i class="fa fa-trash"></i> Delete</a>';
                    $button .= '<a href="'.url('/backend/delete-token/des/'.$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';

                    return $button;
                })
                ->rawColumns(['durasi', 'action'])
                ->make(true)
            ;
        }

        return view('backend.pages.token.index', $data);
    }

    public function store(Request $request)
    {
        $req = $request->all();

        $random = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $req['token'] = substr(str_shuffle(str_repeat($random, 5)), 0, 5);

        $req['status_token'] = 0;

        $nrp = $req['nrp'];
        $count = Token::where('nrp', $nrp)->count();
        $cek_mahasiswa = Mahasiswa::where([['nrp', '=', $nrp], ['status_pilih', '=', 'Sudah']])->count();

        if ($count > 0 || $cek_mahasiswa > 0) {
            if ($cek_mahasiswa > 0) {
                return redirect()->back()->with('danger', 'Kamu sudah menggunakan hak pilihmu');
            }

            return redirect()->back()->with('warning', 'Kamu sudah punya token');
        }
        $result = Token::query()->create($req);

        return redirect('backend/token/show/'.$result->id)->with('success', 'Token berhasil dibuat');
    }

    public function show($id)
    {
        $data['data'] = DB::table('q_token')->where('id', $id)->first();

        return view('backend.pages.token.show', $data);
    }

    public function edit($id)
    {
        $data['data'] = Token::find($id);

        return view('backend.pages.token.edit', $data);
    }

    public function update($id, Request $request)
    {
        $id = $request['id'];
        Token::where('id', $id)->update(['status_token' => 1]);
    }

    public function destroy($id)
    {
        $result = Token::find($id);
        $result->delete();

        return redirect()->back()->with('danger', 'Deleted data');
    }

    public function regenerate(Request $request, $id)
    {
        $req = $request->all();

        $random = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $new_token = substr(str_shuffle(str_repeat($random, 5)), 0, 5);

        $status_token = 0;
        //
        //        $nrp = $req['nrp'];
        $count = Token::where('id', $id)->count();
        $token = Token::where('id', $id)->first();

        $mahasiswa = Mahasiswa::where('nrp', $token->nrp)->first();

        if ('Sudah' == $mahasiswa->status_pilih) {
            return redirect()->back()->with('danger', 'Kamu sudah menggunakan hak pilihmu');
        }
        if ($token->count < 2) {
            $update = Token::where('id', $id)->update(['count' => $token->count + 1, 'token' => $new_token, 'status_token' => $status_token]);

            return redirect()->back()->with('success', 'Berhasil melakukan regenerate token');
        }

        return redirect()->back()->with('danger', 'Kamu sudah 2 kali generate token');
    }
}

app/Http/Controllers/GenToken/TokenController.php
<?php

namespace App\Http\Controllers\GenToken;

use App\Http\Controllers\Controller;
use App\Models\Mahasiswa;
use App\Models\Token;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Datatables;

class TokenController extends Controller
{
    public function index(Request $request)
    {
        $data['data'] = Token::orderBy('id', 'DESC')->get();
        $data['mahasiswa'] = Mahasiswa::where('status_pilih', '=', 'Belum')->get();
        if ($request->ajax()) {
            $token = Token::orderBy('id', 'DESC')->get();

            return DataTables::of($token)
                ->addColumn('durasi', function ($data) {
                    return '<p class="timer" data-create="'.$data->updated_at.'" data-id="'.$data->id.'" data-status="'.$data->status_token.'"></p>';
                })
                ->addColumn('action', function ($data) {
                    return '<a href="'.url('gen-token/regenerate/token/'.$data->id).'" onclick="return confirm('.'`Are you sure?`'.')" class="btn btn-info"><i class="fa fa-pencil"></i> Regenerate</a>';
                })
                ->rawColumns(['durasi', 'action'])
                ->make(true)
            ;
        }

        return view('gen-token.pages.token.index', $data);
    }

    public function store(Request $request)
    {
        $req = $request->all();

        $random = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $req['token'] = substr(str_shuffle(str_repeat($random, 5)), 0, 5);

        $req['status_token'] = 0;

        $nrp = $req['nrp'];
        $count = Token::where('nrp', $nrp)->count();
        $cek_mahasiswa = Mahasiswa::where([['nrp', '=', $nrp], ['status_pilih', '=', 'Sudah']])->count();

        if ($count > 0 || $cek_mahasiswa > 0) {
            if ($cek_mahasiswa > 0) {
                return redirect()->back()->with('danger', 'Kamu sudah menggunakan hak pilihmu');
            }

            return redirect()->back()->with('danger', 'Kamu sudah punya token');
        }
        $result = Token::create($req);

        return redirect()->back()->with('success', 'Token berhasil dibuat');
    }

    public function show($id)
    {
        $data['data'] = DB::table('q_token')->where('id', $id)->first();

        return view('gen-token.pages.token.show', $data);
    }

    public function edit($id)
    {
        $data['data'] = Token::find($id);

        return view('gen-token.pages.token.edit', $data);
    }

    public function update($id, Request $request)
    {
        $id = $request['id'];
        Token::where('id', $id)->update(['status_token' => 1]);
    }

    public function destroy($id)
    {
        $result = Token::find($id);
        $result->delete();

        return redirect()->back()->with('danger', 'delete data');
    }

    public function regenerate(Request $request, $id)
    {
        $req = $request->all();
        $random = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $new_token = substr(str_shuffle(str_repeat($random, 5)), 0, 5);

        $status_token = 0;

        $token = Token::where('id', $id)->first();

        $mahasiswa = Mahasiswa::where('nrp', $token->nrp)->first();

        if ('Sudah' == $mahasiswa->status_pilih) {
            return redirect()->back()->with('danger', 'Kamu sudah menggunakan hak pilihmu');
        }
        if ($token->count < 1) {
            $update = Token::where('id', $id)->update(['count' => $token->count + 1, 'token' => $new_token, 'status_token' => $status_token]);

            return redirect()->back()->with('success', 'Berhasil melakukan regenerate token');
        }

        return redirect()->back()->with('danger', 'Kamu sudah 2 kali generate token');
    }
}

app/Http/Controllers/Panitia/TokenController.php
<?php

namespace App\Http\Controllers\Panitia;

use App\Http\Controllers\Controller;
use App\Models\Mahasiswa;
use App\Models\Token;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TokenController extends Controller
{
    public function index()
    {
        $data['data'] = Token::orderBy('id', 'DESC')->get();
        $data['mahasiswa'] = Mahasiswa::get();

        return view('panitia.pages.token.index', $data);
    }

    public function store(Request $request)
    {
        $req = $request->all();

        $random = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $req['token'] = substr(str_shuffle(str_repeat($random, 5)), 0, 5);

        $req['status_token'] = 0;

        $nrp = $req['nrp'];
        $count = Token::where('nrp', $nrp)->count();
        $cek_mahasiswa = Mahasiswa::where([['nrp', '=', $nrp], ['status_pilih', '=', 'Sudah']])->count();

        if ($count > 0 || $cek_mahasiswa > 0) {
            if ($cek_mahasiswa > 0) {
                return redirect()->back()->with('danger', 'Kamu sudah menggunakan hak memilihmu');
            }

            return redirect()->back()->with('warning', 'NRP has been Registered');
        }
        $result = Token::query()->create($req);

        return redirect('panitia/token/show/'.$result->id)->with('success', 'saved success');
    }

    public function show($id)
    {
        $data['data'] = DB::table('q_token')->where('id', $id)->first();

        return view('panitia.pages.token.show', $data);
    }

    public function edit($id)
    {
        $data['data'] = Token::find($id);

        return view('panitia.pages.token.edit', $data);
    }

    public function update($id, Request $request)
    {
        $id = $request['id'];
        Token::where('id', $id)->update(['status_token' => 1]);
    }

    public function destroy($id)
    {
        $result = Token::find($id);
        $result->delete();

        return redirect('panitia/token')->withInput()->with('message', [
            'title' => 'Yay!',
            'type' => 'success',
            'msg' => 'Deleted data.',
        ]);
    }
}

resources/views/gen-token/pages/token/create.blade.php
@extends('panitia.master')
@section('title')
  Generate Token
@endsection
@section('content')
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        New Data Token
      </h1>
    </section>

    <section class="content">
      <div class="box">
        <form action="{{ url('/gen-token/token') }}" method="post">
          {{ csrf_field() }}
          <div class="box-body">
            <div class="row">
              <div class="col-md-8">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="nrp">NIM</label>
                      <select name="nrp" class="form-control select2" id="nrp">
                        @foreach($mahasiswa as $item)
                          <option value="{{ $item->nrp }}">{{ $item->nrp }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="box-footer text-center">
            <a href="{{ url('/gen-token/token') }}" class="btn btn-warning">Cancel</a>
            <button type="submit" name="submit" class="btn btn-success">Generate</button>
          </div>
        </form>
      </div>
    </section>
  </div>
@stop

resources/views/gen-token/pages/token/edit.blade.php
@extends('backend.master')
@section('title')
  Edit Token
@endsection
@section('content')
  <div class="content-wrapper">
    <section class="content-header">
      <h1>
        Data Token
      </h1>
    </section>

    <section class="content">
      <div class="box">
        <form action="{{ url('/gen-token/token/update2/'.$data->id) }}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="_method" value="PUT">

          <div class="box-body">
            <div class="row">
              <div class="col-md-8">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="nrp">NIM</label>
                      <input type="text" class="form-control" name="nrp" id="nrp" placeholder="NIM" value="{{ $data->nrp }}" readonly required>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="box-footer text-center">
            <a href="{{ url('/gen-token/token') }}" class="btn btn-warning">Cancel</a>
            <button type="submit" name="submit" class="btn btn-success">Generate</button>
          </div>
        </form>
      </div>
    </section>
  </div>
@stop

resources/views/gen-token/pages/token/index.blade.php
@extends('backend.master')
@section('title')
  Token
@endsection
@section('content')
  <div class="main-content">
    @if (\Session::has('success'))

      <div class="alert alert-success" role="alert">
        <a href="#" class="alert-link">{!! \Session::get('success') !!}</a>
      </div>
    @endif
    @if (\Session::has('danger'))

      <div class="alert alert-danger" role="alert">
        maaf <a href="#" class="alert-link">{!! \Session::get('danger') !!}</a>
      </div>
    @endif
    <section class="section">
      <div class="section-header">
        <h1>Token</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="{{url('/backend')}}">Master</a></div>
          <div class="breadcrumb-item">Users</div>
        </div>
      </div>


      <div class="section-body">
        <h2 class="section-title">Generate</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="{{ url('/gen-token/token') }}" method="post">
                {{ csrf_field() }}
                <div class="col-md-8">
                  <div class="form-group">
                    <label></label>
                    <select name="nrp" class="form-control select2" id="nrp">
                      @foreach($mahasiswa as $item)
                        <option value="{{ $item->nrp }}">{{ $item->nrp }}</option>
                      @endforeach
                    </select>
                  </div>
                </div>
                <div class="box-footer text-center">
                  <button type="submit" name="submit" class="btn btn-success">Generate</button>
                </div>
              </form>



              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-striped" id="table">
                    <thead>
                    <tr>
                      <th>NIM</th>
                      <th>Token</th>
                      <th>Status Token</th>
                      <th>Durasi Token</th>
                      <th>Waktu Token</th>
                      <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
{{--                    @foreach($data as $item)--}}

{{--                      <tr>--}}
{{--                        <td>{{ $item->nrp }}</td>--}}
{{--                        <td>{{ $item->token }}</td>--}}
{{--                        <td>{{ $item->status_token }}</td>--}}
{{--                        <td class="timer" data-create="{{$item->updated_at}}" data-id="{{$item->id}}"></td>--}}
{{--                        <td>{{ $item->updated_at }}</td>--}}
{{--                        <td>--}}
{{--                          <form action="{{ url('bem/token/'.$item->id) }}" method="post">--}}
{{--                            {{ csrf_field() }}--}}
{{--                            <a href="{{url('bem/token/'.$item->id)}}" class="btn btn-primary">--}}
{{--                              <i class="fa fa-eye"></i>--}}
{{--                            </a>--}}
{{--                            {{ csrf_field() }}--}}
{{--                            <a href="{{ url('bem/regenerate/token/'.$item->id) }}" onclick="return confirm('Are you sure?')" class="btn btn-info"><i class="fa fa-pencil"></i> Regenerate</a>--}}
{{--                            <input type="hidden" name="_method" value="DELETE">--}}
{{--                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i> Delete</button>--}}
{{--                          </form>--}}
{{--                        </td>--}}
{{--                      </tr>--}}
{{--                    @endforeach--}}

                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

@endsection

@section('js')
  @parent()
  <script type="text/javascript">
    $(document).ready(function(){
      $('#table').DataTable({
        "paging": true,
        "lengthChange": true,
        "searching": true,
        "ordering": false,
        "info": true,
        "autoWidth": false,
        processing: true,
        serverSide: true,
        ajax: {
          url: "{{ route('token.token.index') }}",
        },
        columns: [
          {
            data: 'nrp',
            name: 'nrp'
          },
          {
            data: 'token',
            name: 'token'
          },
          {
            data: 'status_token',
            name: 'status_token',
          },
          {
            data: 'durasi',
            name: 'durasi'
          },
          {
            data: 'updated_at',
            name: 'updated_at'
          },
          {
            data: 'action',
            name: 'action',
            orderable: false
          },
        ],
        "drawCallback": function( settings, json ) {
          // alert( 'DataTables has finished its initialisation.' );
          $('.timer').each(function(i){
            var timer = $(this);
            var id = $(this).attr('data-id');
            var time_in_minutes = 5;
            var current_time = Date.parse($(this).attr('data-create').replace(' ', 'T'));
            var deadline = new Date(current_time + time_in_minutes*60*1000);
            var status = $(this).attr('data-status');

            function time_remaining(endtime){
              var t = Date.parse(endtime) - Date.parse(new Date());
              var seconds = Math.floor( (t/1000) % 60 );
              var minutes = Math.floor( (t/1000/60) % 60 );
              var hours = Math.floor( (t/(1000*60*60)) % 24 );
              var days = Math.floor( t/(1000*60*60*24) );
              return {'total':t, 'days':days, 'hours':hours, 'minutes':minutes, 'seconds':seconds};
            }
            function run_clock(endtime){
              function update_clock(){
                var t = time_remaining(endtime);
                timer.text(t.minutes+'m'+t.seconds+'s');
                if(t.total<=0){
                  clearInterval(timeinterval);
                  timer.text("expired");
                  $.ajax({
                    type : 'put',
                    data : {id : id, _token : '{{csrf_token()}}'},
                    url : "{{url('/gen-token/token/update')}}",
                    success : function(data){
                      timer.prev().text('1');
                    }
                  });
                }

                if(status == '1'){
                  timer.text("expired");
                }

              }
              update_clock();
              var timeinterval = setInterval(update_clock,1000);
            }
            run_clock(deadline);
          });
        }
      });




    });

  </script>
@endsection

resources/views/gen-token/pages/token/show.blade.php
@extends('backend.master')
@section('title')
  Token
@endsection
@section('content')
  <div class="main-content">
    <section class="section">
      <div class="section-header">
        <h1>Token</h1>
        <div class="section-header-breadcrumb">
          <div class="breadcrumb-item active"><a href="{{url('/gen-token')}}">Master</a></div>
          <div class="breadcrumb-item">Users</div>
        </div>
      </div>


      <div class="section-body">
        <h2 class="section-title">Generate</h2>

        <div class="row">
          <div class="col-12">
            <div class="card">
              <form action="" method="post">
                {{ csrf_field() }}
                <div class="card-body">
                  <input type="hidden" name="_method" value="PUT">
                  <div class="box-body">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="row">
                          <div class="col-md-12">
                            <table class="table table-condensed">
                              <tr>
                                <td>Nama</td><td>{{ $data->nama }}</td>
                              </tr>
                              <tr>
                                <td>NIM</td><td>{{ $data->nrp }}</td>
                              </tr>
                              <tr>
                                <td>Token</td><td class="token">{{ $data->token }}</td>
                              </tr>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="box-footer text-center">
                    <a href="{{ url('/gen-token/token') }}" class="btn btn-warning">Back</a>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
@stop